### ISSUE TITLE
can't npm install this module

### ISSUE THREAD

**Issue by harlantwood** [coasys/ad4m-cli#1]
on mac, I tried to 

```
npm i @perspect3vism/ad4m-cli
```

but after a lot of work, it ended in:

```
npm ERR! code 1
npm ERR! path /Users/harlan/code/wikinodes/apps/tree-of-life/ad4m/node_modules/@perspect3vism/ad4m-cli
npm ERR! command failed
npm ERR! command sh -c ln -sf node_modules/@perspect3vism/ad4m-executor/default.nix default.nix && nix-shell --run ./scripts/createHolochainSymlinks.sh && node scripts/get-builtin-langs.js
npm ERR! error: getting status of '/Users/harlan/code/wikinodes/apps/tree-of-life/ad4m/node_modules/@perspect3vism/ad4m-cli/node_modules/@perspect3vism/ad4m-executor/default.nix': No such file or directory
```

note that I can run the cli from the github repo checked out elsewhere on my machine.

**Comment by lucksus** [comment]
It worked on my macBook with macOS 11.2.3.

Were there other errors before this one? I would guess that installing @perspect3vism/ad4m-executor failed which is why the postinstall command can't find it in node_modules.

What node version are you running? I believe there is some dep in ad4m-executor that needs >=14.15.

**Comment by harlantwood** [comment]
Info:
- OSX 11.4 (Big Sur)
- Node v14.17.5
- npm v7.21.1

Expand arrows to see output:


<details>
 <summary>$ npm i @perspect3vism/ad4m-cli</summary>


$ npm i @perspect3vism/ad4m-cli

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated apollo-tracing@0.15.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
npm WARN deprecated ipld-raw@6.0.0: This module has been superseded by the multiformats module
npm WARN deprecated graphql-extensions@0.15.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated ipld-dag-cbor@0.17.1: This module has been superseded by @ipld/dag-cbor and multiformats
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated apollo-cache-control@0.14.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated ipld-dag-pb@0.20.0: This module has been superseded by @ipld/dag-pb and multiformats
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated ipfs-block-service@0.18.0: This module has been merged into ipfs
npm WARN deprecated libp2p-noise@2.0.5: This repository is now being maintained by ChainSafe, and can be found at https://github.com/ChainSafe/js-libp2p-noise under @chainsafe/libp2p-noise
npm WARN deprecated ipld@0.28.0: Please use the multiformats module instead
npm WARN deprecated graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
npm WARN deprecated multihashing@0.3.4: This module has been superseded by the multiformats module
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/harlan/code/node_modules/@perspect3vism/ad4m-cli
npm ERR! command failed
npm ERR! command sh -c ln -sf node_modules/@perspect3vism/ad4m-executor/default.nix default.nix && nix-shell --run ./scripts/createHolochainSymlinks.sh && node scripts/get-builtin-langs.js
npm ERR! error: getting status of '/Users/harlan/code/node_modules/@perspect3vism/ad4m-cli/node_modules/@perspect3vism/ad4m-executor/default.nix': No such file or directory

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/harlan/.npm/_logs/2021-08-29T07_03_31_131Z-debug.log
</details>

<details>
 <summary>/Users/harlan/.npm/_logs/2021-08-29T07_03_31_131Z-debug.log</summary>
0 verbose cli [
0 verbose cli   '/Users/harlan/.nvm/versions/node/v14.17.5/bin/node',
0 verbose cli   '/Users/harlan/.nvm/versions/node/v14.17.5/bin/npm',
0 verbose cli   'i',
0 verbose cli   '@perspect3vism/ad4m-cli'
0 verbose cli ]
1 info using npm@7.21.1
2 info using node@v14.17.5
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms

[snip]

9483 timing reify:rollback:retireShallow Completed in 0ms
9484 timing command:install Completed in 226194ms
9485 verbose stack Error: command failed
9485 verbose stack     at ChildProcess.<anonymous> (/Users/harlan/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
9485 verbose stack     at ChildProcess.emit (events.js:400:28)
9485 verbose stack     at maybeClose (internal/child_process.js:1055:16)
9485 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
9486 verbose pkgid @perspect3vism/ad4m-cli@0.0.2
9487 verbose cwd /Users/harlan/code/wikinodes/spikes
9488 verbose Darwin 20.5.0
9489 verbose argv "/Users/harlan/.nvm/versions/node/v14.17.5/bin/node" "/Users/harlan/.nvm/versions/node/v14.17.5/bin/npm" "i" "@perspect3vism/ad4m-cli"
9490 verbose node v14.17.5
9491 verbose npm  v7.21.1
9492 error code 1
9493 error path /Users/harlan/code/node_modules/@perspect3vism/ad4m-cli
9494 error command failed
9495 error command sh -c ln -sf node_modules/@perspect3vism/ad4m-executor/default.nix default.nix && nix-shell --run ./scripts/createHolochainSymlinks.sh && node scripts/get-builtin-langs.js
9496 error error: getting status of '/Users/harlan/code/node_modules/@perspect3vism/ad4m-cli/node_modules/@perspect3vism/ad4m-executor/default.nix': No such file or directory
9497 verbose exit 1
</details>

**Comment by harlantwood** [comment]
@lucksus @jacob3141 it's looking for:

MY_PROJECT/node_modules/@perspect3vism/ad4m-cli/node_modules/@perspect3vism/ad4m-executor/default.nix

but this is during the installation of ad4m-cli, so

**Comment by harlantwood** [comment]
@lucksus @jacob3141 it's looking for:

MY_PROJECT/node_modules/@perspect3vism/ad4m-cli/node_modules/@perspect3vism/ad4m-executor/default.nix

but this is during the installation of ad4m-cli, so 

MY_PROJECT/node_modules/@perspect3vism/ad4m-cli

does not exist (well, at least not after the failure, when I can check:)

ls -lFG node_modules/@perspect3vism/
total 0
drwxr-xr-x  9 harlan  staff  288 Aug 29 17:49 ad4m/
drwxr-xr-x  7 harlan  staff  224 Aug 29 17:49 ad4m-executor/

I did install ad4m-executor, as you can see, so maybe if it was a peer dependency and we looked in:

node_modules/@perspect3vism/ad4m-executor/default.nix

that would solve it for me?  not sure if that's skirting the root issue though.
